# Generated by Django 5.2 on 2025-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerId', models.CharField(max_length=100, unique=True)),
                ('questionId', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnsweredQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerId', models.CharField(max_length=100)),
                ('questionId', models.CharField(max_length=100)),
                ('customAnswer', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('questionnaireId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.CharField(max_length=100, unique=True)),
                ('groupId', models.CharField(max_length=100)),
                ('typeQuestion_idTypeQuestion', models.CharField(max_length=100)),
                ('typeQuestion_description', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireId', models.CharField(max_length=100, unique=True)),
                ('questionnaireName', models.CharField(max_length=100)),
                ('dateInsert', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireId', models.CharField(max_length=100)),
                ('dateInsert', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
