# Generated by Django 5.2 on 2025-04-23 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluatorClass', models.CharField(default='Evaluator', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionGroup', to='questionnaire.group')),
                ('question_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionQuestionnaire', to='questionnaire.questionnaire')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionType', to='questionnaire.type')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('custom_answer', models.TextField(blank=True, null=True)),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerQuestion', to='questionnaire.question')),
            ],
        ),
    ]
