# Generated by Django 5.2 on 2025-05-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.IntegerField(),
        ),
    ]
