# Generated by Django 5.2 on 2025-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestions',
            name='userId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
