# Generated by Django 5.2 on 2025-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_answeredquestions_userid_alter_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestions',
            name='answerId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
