# Generated by Django 5.2 on 2025-05-21 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_answeredquestions_answerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestions',
            name='dateAnswer',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
