# Generated by Django 4.2.11 on 2025-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_answeredquestions_dateanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestions',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='questionnaire/media/uploads/'),
        ),
    ]
