# Generated by Django 4.2.11 on 2025-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_answeredquestions_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestions',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
