# Generated by Django 4.2.11 on 2025-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_alter_answeredquestions_dateanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairevalue',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnairevalue',
            name='dateInsert',
            field=models.DateField(auto_now_add=True),
        ),
    ]
