# Generated by Django 5.2 on 2025-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_questionnairevalue_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestions',
            name='dateAnswer',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionnairevalue',
            name='dateInsert',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
