# Generated by Django 5.2 on 2025-05-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_alter_answeredquestions_dateanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestions',
            name='dateAnswer',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionnairevalue',
            name='dateInsert',
            field=models.DateField(auto_now_add=True),
        ),
    ]
