# Generated by Django 5.2 on 2025-05-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_alter_answeredquestions_dateanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestions',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
