# Generated by Django 5.2 on 2025-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_alter_answeredquestions_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredquestions',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='answeredquestions',
            name='uploaded_files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
